version: "3"
services:
  # use products and users later for the service names
  web:
    image: steadylearner/ubuntu-node
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:

