# Relevant to docker container
FROM steadylearner/ubuntu_node

WORKDIR /app

COPY . /app

EXPOSE 3000 

# It will be executed whenever you run the image and make instances(containers) of it
CMD ["yarn", "serve"]
