# It is used with $docker build command

FROM steadylearner/ubuntu-node
# MAINTAINER steadylearner www.steadylearner.com

EXPOSE 3000

# RUN install relevant commands

# 8888 will be used instead of 3000 in your localhost with the command below
# $docker run -it -p 8888:3000 steadylearner/ubuntu-node bash
# $cd /home/node && yarn serve
# and you can see the result with http://0.0.0.0:8888/

# should learn more about Dockerfile and find this work in localhost or container
# https://www.google.com/search?q=how+to+use+Dockerfile
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
#WORKDIR ~/home/node
#CMD ["yarn", "serve"] app execution relevant, after RUN
# test it work with this file in another directory
