# https://docs.docker.com/compose/compose-file/

version: "3"
services:
  products:
    image: steadylearner/products:latest
    container_name: products
    ports:
      - "80:8000"
    env_file:
      - gRPC.env
    command: yarn serve
    depends_on:
      - grpc_postgresql
      - user_product
    networks:
      - grpc
    # https://www.google.com/search?&q=what+is+docker+health+check
    healthcheck:
      test: curl --fail -s http://localhost:8000/product || exit 1
      interval: 1m
      timeout: 10s
  user_product:
    image: steadylearner/user_product:latest
    container_name: user_product
    env_file:
      - gRPC.env
    command: yarn serve
    depends_on:
      - grpc_postgresql
    networks:
      - grpc
    healthcheck:
      test: curl --fail -s http://localhost:50051 || exit 1
      interval: 1m
      timeout: 10s
  grpc_postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres
    container_name: grpc_postgresql
    # https://docs.docker.com/compose/compose-file/#volumes
    volumes:
       - db/etc/postgresql
       - db/var/log/postgresql
       - db/var/lib/postgresql
    networks:
      - grpc
networks:
  grpc:
volumes:
  db:




